# Generated by Django 3.2.8 on 2021-10-10 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='test_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.test'),
        ),
        migrations.AlterField(
            model_name='planremoval',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.test'),
        ),
    ]
